### ISSUE TITLE
Microsoft.VC90.CRT.manifest could not be extracted!

### ISSUE THREAD

**Issue by xravian** [EvilCult/moviecatcher#10]
下载Movie.Catcher.for.Windows.zip，解压缩到D盘根目录，双击exe运行，报错：Microsoft.VC90.CRT.manifest could not be extracted!，环境：Windows10 Pro X64，不清楚是不是因为中文用户名的原因。

参考：https://github.com/pyinstaller/pyinstaller/issues/1866

**Comment by EvilCult** [comment]
好像是。。。。
连参考都找了。。。。好高端。。。感谢。。。
我先研究研究。。感觉是个复杂的问题。。。

**Comment by ddkk3000** [comment]
没法用呀，我也是，两个软件都是
