### ISSUE TITLE
python并发

### ISSUE THREAD

**Issue by MrLevo520** [EvilCult/moviecatcher#13]
建议改进使用threading作为并发搜索的方法，使用多进程代替多线程应该会好一点吧？不过介于这个目前还是个小的app，搜索的情况不会太差，以后资源网站池更多的话，建议使用multiprocessing包会好一点，纯粹是建议，只是刚好源码读到这~项目很棒，等有时间了我会给你pull requests的哈哈哈哈

**Comment by EvilCult** [comment]
多谢建议，技术渣一枚，threading这一块还没搞太明白。。。（手动捂脸）。。
我去多研究研究，multiprocessing。哈哈哈～～期待dalao的pull requests～～
