### ISSUE TITLE
关于资源接口

### ISSUE THREAD

**Issue by Virace** [EvilCult/moviecatcher#15]
因为搜索过程很慢，所以看了一下接口发现是在用PC版zimuzu网站直接进行解析的
1.字幕组网站在正常时间短访问就不是特别流畅(相比下)
2.直接获取网页内容后解析也会有些影响速度

推荐使用字幕组手机客户端版的接口，有兴趣可以考虑抓一下。
也可以留下联系方式(邮箱)，可以直接把这几个接口直接发给你~

**Comment by ijustknow** [comment]
这的确是个好建议！
