### ISSUE TITLE
Mac下使用搜狗五笔无法输入中文

### ISSUE THREAD

**Issue by zhouhounan** [EvilCult/moviecatcher#19]
Mac下使用搜狗五笔无法输入中文
还有啥时候更新资源抓取源呀
连起跑线出了好几个月的都没有
![image](https://user-images.githubusercontent.com/17348292/32366893-2663971e-c04e-11e7-8493-d9476c6fbdb2.png)

**Comment by jijiucheng** [comment]
同问
