### ISSUE TITLE
mac os 10.12.6打开就在dock栏一闪一闪然后就退出了。

### ISSUE THREAD

**Issue by fckcg** [EvilCult/moviecatcher#2]

**Comment by EvilCult** [comment]
那可能是与系统某些设置冲突了。
可以右击app，选择「显示包内容」，然后依次进入「Contents」->「MacOS」，然后双击那个黑色「Movie Catcher」的文件。应该会弹出一个黑色的终端，可以把里面的报错内容复制给我。

**Comment by qydxyx** [comment]
high Sierra 也遇到相同问题，也是跳了一跳就没了
<img width="682" alt="screen shot 2017-09-27 at 14 43 59" src="https://user-images.githubusercontent.com/32056520/30939513-80fc4c30-a392-11e7-97f4-ea5fe78870ce.png">

**Comment by AugustRush** [comment]
一样

**Comment by EvilCult** [comment]
看报错，应该是系统权限问题，导致创建配置文件的时候失败了。
可以看一下「/Users/{你的用户名}/Library/Application Support/」目录下有没有「Movie Catcher」文件夹。
如果没有可以尝试一下修复磁盘权限，
或者重置home目录的用户权限[https://support.apple.com/zh-cn/HT203538](https://support.apple.com/zh-cn/HT203538)

**Comment by qydxyx** [comment]
哥你是我救星啊！！！虽然movie catcher跳一跳退出的问题没有解决，不过重置home目录用户权限后我karabiner elements长期以来启动后闪退的问题意外解决了！感动
btw，修复磁盘权限咋操作？

**Comment by qydxyx** [comment]
修复磁盘权限后也一样，还是开不起来

**Comment by EvilCult** [comment]
感觉上就是权限问题。。「karabiner elements」大概就是这问题读不到自己的Storage所以闪退。
但是为何Movie Catcher依旧不行。。。。。诡异。。。。
这样，打开「Finder」，然后在菜单栏，按住「option」键点击「前往」，选择下面的「资源库」，然后找到「Application Support」这个文件夹，进入，里面会有很多文件夹了，看看有没有「Movie Catcher」文件夹。
如果有，删掉试试；如果没有，看看「Application Support」这个文件夹的全县，是否你的用户具备“读与写”权限。。。。

**Comment by qydxyx** [comment]
<img width="682" alt="screen shot 2017-09-28 at 00 53 06" src="https://user-images.githubusercontent.com/32056520/30955149-7fb16fae-a3e7-11e7-8054-de6982ead847.png">
Application Support 依然没有 Movie Catcher 的文件夹，并且权限也是可以读与写的，但问题依旧。重新点开了之前的终端，还是一样的内容

**Comment by EvilCult** [comment]
呃，写一个创建文件夹的程序你试试。。
麻烦下载这个文件：[mkdir.zip](https://github.com/EvilCult/moviecatcher/files/1340081/mkdir.zip)；
解压，打开终端，把mkdir.py文件拖进去，敲回车。看一下终端提示什么错误？？

**Comment by qydxyx** [comment]
<img width="682" alt="screen shot 2017-09-28 at 12 06 07" src="https://user-images.githubusercontent.com/32056520/30985583-82d5791a-a445-11e7-9a48-bd80e54f7e73.png">
显示的这个，好奇怪啊，我电脑 Users 文件夹下面并没有 JoeChen 这个文件夹呀。可能是我最开始电脑刚设置的时候改了用户名的缘故？

**Comment by EvilCult** [comment]
果然如此。。。。嗯，是改过了用户名，但是home文件夹的目录名并没有改变。还是之前的。。所以找不到，也就没办法写入。
这个问题貌似一开始就忽略了。。。让我想想如何解决这个bug。

多谢配合。辛苦。💦

**Comment by qydxyx** [comment]
我才应该感谢，karabiner elements总算能用了，感动哭

**Comment by EvilCult** [comment]
客气～重新发布了一次，版本号并没有改变，你可以在releases里再下载一次试试。
应该可以了。

**Comment by qydxyx** [comment]
哇，这次可以了
