### ISSUE TITLE
关于百度云在线观看代码

### ISSUE THREAD

**Issue by MrLevo520** [EvilCult/moviecatcher#20]
你好,我读源码的时候发现获取url那个代码片段，始终没有找到百度云的挂链，代码中只有获取磁力链接的页面，百度云的资源页面找不到啊，人工模拟点进去也是空的资源，不知道app是怎么获取到百度云的链接的，求告知

**Comment by MrLevo520** [comment]
解决了，原来是磁力链接转化为百度云的离线任务，一直再找百度云的链接，结果走错路了，哈哈，还有这种操作！

**Comment by ijustknow** [comment]
@MrLevo520 大神不愧是大神，对吧
