### ISSUE TITLE
请教, 如何才能让MovieCatcher自动调用Aria2GUI呢?

### ISSUE THREAD

**Issue by linxiang-dev** [EvilCult/moviecatcher#3]
直接点击离线下载, 弹出包含具体下载链接的窗口, 再点击下载默认会用Safari打开, 然后就触发浏览器的下载了...
看使用说明貌似是可以直接调用Aria2GUI的, 请问具体应该如何实现...?

**Comment by EvilCult** [comment]
Aria2Gui相关的功能，在上一次更新，被隐藏了。&& 会在下一次更新or下下次更新放出。
主要是Win系统下，并没有发现好用的Aria2的客户端，所以要处理一个分支。Mac默认使用Aria2Gui，Win下。。。我还在找好用的。。
