### ISSUE TITLE
MacBook 百度云不能登陆

### ISSUE THREAD

**Issue by hugh1li** [EvilCult/moviecatcher#8]
明明装了chrome的。
<img width="412" alt="screen shot 2017-09-28 at 22 57 42" src="https://user-images.githubusercontent.com/6027595/30999052-8b342704-a4a0-11e7-95d7-c56844cfbf09.png">

**Comment by EvilCult** [comment]
需要一个神奇版本的Chrome。。。介于59～61。

具体原因见这个回答：#4
