### ISSUE TITLE
点击登陆百度云，弹出对话框，然后对话框消失，没有登陆成功

### ISSUE THREAD

**Issue by ijustknow** [EvilCult/moviecatcher#9]
百度云未登陆成功前，“以下为低质量资源”下面的条目点了，出来的对话框中还有内容，登陆成功后，试了起码5部影片，低质量资源下面的点完全部弹出对话框，但里面没有任何内容

**Comment by EvilCult** [comment]
看起来，就是网络问题。。。。慢。。
